name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd compiler
        cargo build --verbose
    - name: Run tests
      run: |
        cd compiler
        cargo test --verbose
